name: Publish to npm on push to main

on:
  push:
    branches:
      - main
    paths:
      - "aa/**"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"

      - name: Install Dependencies
        run: npm ci

      - name: Build and Test
        run: |
          npm run build
          npm test

      - name: Commit, Push, and Publish
        run: |
          if git log -1 --pretty=%B | grep -q "chore: release"; then
            echo "Skipping: This is a release commit from a previous run."
            exit 0
          fi

          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          # Add the generated dist directory to the staging area
          git add dist

          # Create the version bump commit. If dist was changed, it will be included.
          npm version patch -m "chore: release %s"

          # Push the commit and the new tag
          git push
          git push --tags

          # Publish to npm
          npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
